'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace anamaria
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ServiceSoap", [Namespace]:="http://www.oticasanamaria.net.br/wins/")>  _
    Partial Public Class Service
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private Importa_produtoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Saldo_produtoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private incluir_listagem_estoqueOperationCompleted As System.Threading.SendOrPostCallback
        
        Private logarOperationCompleted As System.Threading.SendOrPostCallback
        
        Private os_com_andamentosOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Andamentos_labonorte_matrizOperationCompleted As System.Threading.SendOrPostCallback
        
        Private trans_filial_matrizOperationCompleted As System.Threading.SendOrPostCallback
        
        Private trans_filial_matriz_dsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private tem_filaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private trans_matriz_filialOperationCompleted As System.Threading.SendOrPostCallback
        
        Private trans_matriz_filial_nregOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Marca_transmitidoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private devolve_importadosOperationCompleted As System.Threading.SendOrPostCallback
        
        Private R360OperationCompleted As System.Threading.SendOrPostCallback
        
        Private cfOperationCompleted As System.Threading.SendOrPostCallback
        
        Private RPontuacaoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private RGiroOperationCompleted As System.Threading.SendOrPostCallback
        
        Private OS_SemanaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private exporta_produtoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private os_inOperationCompleted As System.Threading.SendOrPostCallback
        
        Private os_retransOperationCompleted As System.Threading.SendOrPostCallback
        
        Private os_OutOperationCompleted As System.Threading.SendOrPostCallback
        
        Private os_Out_laboOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.BTSistemas.My.MySettings.Default.mrotica_2008_anamaria_Service
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event Importa_produtoCompleted As Importa_produtoCompletedEventHandler
        
        '''<remarks/>
        Public Event Saldo_produtoCompleted As Saldo_produtoCompletedEventHandler
        
        '''<remarks/>
        Public Event incluir_listagem_estoqueCompleted As incluir_listagem_estoqueCompletedEventHandler
        
        '''<remarks/>
        Public Event logarCompleted As logarCompletedEventHandler
        
        '''<remarks/>
        Public Event os_com_andamentosCompleted As os_com_andamentosCompletedEventHandler
        
        '''<remarks/>
        Public Event Andamentos_labonorte_matrizCompleted As Andamentos_labonorte_matrizCompletedEventHandler
        
        '''<remarks/>
        Public Event trans_filial_matrizCompleted As trans_filial_matrizCompletedEventHandler
        
        '''<remarks/>
        Public Event trans_filial_matriz_dsCompleted As trans_filial_matriz_dsCompletedEventHandler
        
        '''<remarks/>
        Public Event tem_filaCompleted As tem_filaCompletedEventHandler
        
        '''<remarks/>
        Public Event trans_matriz_filialCompleted As trans_matriz_filialCompletedEventHandler
        
        '''<remarks/>
        Public Event trans_matriz_filial_nregCompleted As trans_matriz_filial_nregCompletedEventHandler
        
        '''<remarks/>
        Public Event Marca_transmitidoCompleted As Marca_transmitidoCompletedEventHandler
        
        '''<remarks/>
        Public Event devolve_importadosCompleted As devolve_importadosCompletedEventHandler
        
        '''<remarks/>
        Public Event R360Completed As R360CompletedEventHandler
        
        '''<remarks/>
        Public Event cfCompleted As cfCompletedEventHandler
        
        '''<remarks/>
        Public Event RPontuacaoCompleted As RPontuacaoCompletedEventHandler
        
        '''<remarks/>
        Public Event RGiroCompleted As RGiroCompletedEventHandler
        
        '''<remarks/>
        Public Event OS_SemanaCompleted As OS_SemanaCompletedEventHandler
        
        '''<remarks/>
        Public Event exporta_produtoCompleted As exporta_produtoCompletedEventHandler
        
        '''<remarks/>
        Public Event os_inCompleted As os_inCompletedEventHandler
        
        '''<remarks/>
        Public Event os_retransCompleted As os_retransCompletedEventHandler
        
        '''<remarks/>
        Public Event os_OutCompleted As os_OutCompletedEventHandler
        
        '''<remarks/>
        Public Event os_Out_laboCompleted As os_Out_laboCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.oticasanamaria.net.br/wins/Importa_produto", RequestNamespace:="http://www.oticasanamaria.net.br/wins/", ResponseNamespace:="http://www.oticasanamaria.net.br/wins/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Importa_produto(ByVal x_cod_tabela As Long, ByVal tipo As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("Importa_produto", New Object() {x_cod_tabela, tipo})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Importa_produtoAsync(ByVal x_cod_tabela As Long, ByVal tipo As String)
            Me.Importa_produtoAsync(x_cod_tabela, tipo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Importa_produtoAsync(ByVal x_cod_tabela As Long, ByVal tipo As String, ByVal userState As Object)
            If (Me.Importa_produtoOperationCompleted Is Nothing) Then
                Me.Importa_produtoOperationCompleted = AddressOf Me.OnImporta_produtoOperationCompleted
            End If
            Me.InvokeAsync("Importa_produto", New Object() {x_cod_tabela, tipo}, Me.Importa_produtoOperationCompleted, userState)
        End Sub
        
        Private Sub OnImporta_produtoOperationCompleted(ByVal arg As Object)
            If (Not (Me.Importa_produtoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Importa_produtoCompleted(Me, New Importa_produtoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.oticasanamaria.net.br/wins/Saldo_produto", RequestNamespace:="http://www.oticasanamaria.net.br/wins/", ResponseNamespace:="http://www.oticasanamaria.net.br/wins/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Saldo_produto(ByVal x_cod_produto As Integer, ByVal x_id_filial As Integer) As Integer
            Dim results() As Object = Me.Invoke("Saldo_produto", New Object() {x_cod_produto, x_id_filial})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Saldo_produtoAsync(ByVal x_cod_produto As Integer, ByVal x_id_filial As Integer)
            Me.Saldo_produtoAsync(x_cod_produto, x_id_filial, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Saldo_produtoAsync(ByVal x_cod_produto As Integer, ByVal x_id_filial As Integer, ByVal userState As Object)
            If (Me.Saldo_produtoOperationCompleted Is Nothing) Then
                Me.Saldo_produtoOperationCompleted = AddressOf Me.OnSaldo_produtoOperationCompleted
            End If
            Me.InvokeAsync("Saldo_produto", New Object() {x_cod_produto, x_id_filial}, Me.Saldo_produtoOperationCompleted, userState)
        End Sub
        
        Private Sub OnSaldo_produtoOperationCompleted(ByVal arg As Object)
            If (Not (Me.Saldo_produtoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Saldo_produtoCompleted(Me, New Saldo_produtoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.oticasanamaria.net.br/wins/incluir_listagem_estoque", RequestNamespace:="http://www.oticasanamaria.net.br/wins/", ResponseNamespace:="http://www.oticasanamaria.net.br/wins/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function incluir_listagem_estoque(ByVal OS As Integer, ByVal filial As Integer, ByVal estoque As Integer) As String
            Dim results() As Object = Me.Invoke("incluir_listagem_estoque", New Object() {OS, filial, estoque})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub incluir_listagem_estoqueAsync(ByVal OS As Integer, ByVal filial As Integer, ByVal estoque As Integer)
            Me.incluir_listagem_estoqueAsync(OS, filial, estoque, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub incluir_listagem_estoqueAsync(ByVal OS As Integer, ByVal filial As Integer, ByVal estoque As Integer, ByVal userState As Object)
            If (Me.incluir_listagem_estoqueOperationCompleted Is Nothing) Then
                Me.incluir_listagem_estoqueOperationCompleted = AddressOf Me.Onincluir_listagem_estoqueOperationCompleted
            End If
            Me.InvokeAsync("incluir_listagem_estoque", New Object() {OS, filial, estoque}, Me.incluir_listagem_estoqueOperationCompleted, userState)
        End Sub
        
        Private Sub Onincluir_listagem_estoqueOperationCompleted(ByVal arg As Object)
            If (Not (Me.incluir_listagem_estoqueCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent incluir_listagem_estoqueCompleted(Me, New incluir_listagem_estoqueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.oticasanamaria.net.br/wins/logar", RequestNamespace:="http://www.oticasanamaria.net.br/wins/", ResponseNamespace:="http://www.oticasanamaria.net.br/wins/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function logar(ByVal loja As Integer, ByVal cred As String) As Integer
            Dim results() As Object = Me.Invoke("logar", New Object() {loja, cred})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub logarAsync(ByVal loja As Integer, ByVal cred As String)
            Me.logarAsync(loja, cred, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub logarAsync(ByVal loja As Integer, ByVal cred As String, ByVal userState As Object)
            If (Me.logarOperationCompleted Is Nothing) Then
                Me.logarOperationCompleted = AddressOf Me.OnlogarOperationCompleted
            End If
            Me.InvokeAsync("logar", New Object() {loja, cred}, Me.logarOperationCompleted, userState)
        End Sub
        
        Private Sub OnlogarOperationCompleted(ByVal arg As Object)
            If (Not (Me.logarCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent logarCompleted(Me, New logarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.oticasanamaria.net.br/wins/os_com_andamentos", RequestNamespace:="http://www.oticasanamaria.net.br/wins/", ResponseNamespace:="http://www.oticasanamaria.net.br/wins/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function os_com_andamentos(ByVal cod_os As Integer, ByVal filial As Integer) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("os_com_andamentos", New Object() {cod_os, filial})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub os_com_andamentosAsync(ByVal cod_os As Integer, ByVal filial As Integer)
            Me.os_com_andamentosAsync(cod_os, filial, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub os_com_andamentosAsync(ByVal cod_os As Integer, ByVal filial As Integer, ByVal userState As Object)
            If (Me.os_com_andamentosOperationCompleted Is Nothing) Then
                Me.os_com_andamentosOperationCompleted = AddressOf Me.Onos_com_andamentosOperationCompleted
            End If
            Me.InvokeAsync("os_com_andamentos", New Object() {cod_os, filial}, Me.os_com_andamentosOperationCompleted, userState)
        End Sub
        
        Private Sub Onos_com_andamentosOperationCompleted(ByVal arg As Object)
            If (Not (Me.os_com_andamentosCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent os_com_andamentosCompleted(Me, New os_com_andamentosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.oticasanamaria.net.br/wins/Andamentos_labonorte_matriz", RequestNamespace:="http://www.oticasanamaria.net.br/wins/", ResponseNamespace:="http://www.oticasanamaria.net.br/wins/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Andamentos_labonorte_matriz(ByVal filial As Integer, ByVal os As Integer, ByRef ds As System.Data.DataSet) As String
            Dim results() As Object = Me.Invoke("Andamentos_labonorte_matriz", New Object() {filial, os, ds})
            ds = CType(results(1),System.Data.DataSet)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Andamentos_labonorte_matrizAsync(ByVal filial As Integer, ByVal os As Integer, ByVal ds As System.Data.DataSet)
            Me.Andamentos_labonorte_matrizAsync(filial, os, ds, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Andamentos_labonorte_matrizAsync(ByVal filial As Integer, ByVal os As Integer, ByVal ds As System.Data.DataSet, ByVal userState As Object)
            If (Me.Andamentos_labonorte_matrizOperationCompleted Is Nothing) Then
                Me.Andamentos_labonorte_matrizOperationCompleted = AddressOf Me.OnAndamentos_labonorte_matrizOperationCompleted
            End If
            Me.InvokeAsync("Andamentos_labonorte_matriz", New Object() {filial, os, ds}, Me.Andamentos_labonorte_matrizOperationCompleted, userState)
        End Sub
        
        Private Sub OnAndamentos_labonorte_matrizOperationCompleted(ByVal arg As Object)
            If (Not (Me.Andamentos_labonorte_matrizCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Andamentos_labonorte_matrizCompleted(Me, New Andamentos_labonorte_matrizCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.oticasanamaria.net.br/wins/trans_filial_matriz", RequestNamespace:="http://www.oticasanamaria.net.br/wins/", ResponseNamespace:="http://www.oticasanamaria.net.br/wins/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function trans_filial_matriz(ByVal tbinst As System.Data.DataSet, ByVal origem As Integer) As String
            Dim results() As Object = Me.Invoke("trans_filial_matriz", New Object() {tbinst, origem})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub trans_filial_matrizAsync(ByVal tbinst As System.Data.DataSet, ByVal origem As Integer)
            Me.trans_filial_matrizAsync(tbinst, origem, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub trans_filial_matrizAsync(ByVal tbinst As System.Data.DataSet, ByVal origem As Integer, ByVal userState As Object)
            If (Me.trans_filial_matrizOperationCompleted Is Nothing) Then
                Me.trans_filial_matrizOperationCompleted = AddressOf Me.Ontrans_filial_matrizOperationCompleted
            End If
            Me.InvokeAsync("trans_filial_matriz", New Object() {tbinst, origem}, Me.trans_filial_matrizOperationCompleted, userState)
        End Sub
        
        Private Sub Ontrans_filial_matrizOperationCompleted(ByVal arg As Object)
            If (Not (Me.trans_filial_matrizCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent trans_filial_matrizCompleted(Me, New trans_filial_matrizCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.oticasanamaria.net.br/wins/trans_filial_matriz_ds", RequestNamespace:="http://www.oticasanamaria.net.br/wins/", ResponseNamespace:="http://www.oticasanamaria.net.br/wins/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function trans_filial_matriz_ds(ByVal tbinst As System.Data.DataSet, ByVal origem As Integer, ByRef dsRet As System.Data.DataSet) As String
            Dim results() As Object = Me.Invoke("trans_filial_matriz_ds", New Object() {tbinst, origem, dsRet})
            dsRet = CType(results(1),System.Data.DataSet)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub trans_filial_matriz_dsAsync(ByVal tbinst As System.Data.DataSet, ByVal origem As Integer, ByVal dsRet As System.Data.DataSet)
            Me.trans_filial_matriz_dsAsync(tbinst, origem, dsRet, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub trans_filial_matriz_dsAsync(ByVal tbinst As System.Data.DataSet, ByVal origem As Integer, ByVal dsRet As System.Data.DataSet, ByVal userState As Object)
            If (Me.trans_filial_matriz_dsOperationCompleted Is Nothing) Then
                Me.trans_filial_matriz_dsOperationCompleted = AddressOf Me.Ontrans_filial_matriz_dsOperationCompleted
            End If
            Me.InvokeAsync("trans_filial_matriz_ds", New Object() {tbinst, origem, dsRet}, Me.trans_filial_matriz_dsOperationCompleted, userState)
        End Sub
        
        Private Sub Ontrans_filial_matriz_dsOperationCompleted(ByVal arg As Object)
            If (Not (Me.trans_filial_matriz_dsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent trans_filial_matriz_dsCompleted(Me, New trans_filial_matriz_dsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.oticasanamaria.net.br/wins/tem_fila", RequestNamespace:="http://www.oticasanamaria.net.br/wins/", ResponseNamespace:="http://www.oticasanamaria.net.br/wins/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function tem_fila(ByVal filial As Integer) As Boolean
            Dim results() As Object = Me.Invoke("tem_fila", New Object() {filial})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub tem_filaAsync(ByVal filial As Integer)
            Me.tem_filaAsync(filial, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub tem_filaAsync(ByVal filial As Integer, ByVal userState As Object)
            If (Me.tem_filaOperationCompleted Is Nothing) Then
                Me.tem_filaOperationCompleted = AddressOf Me.Ontem_filaOperationCompleted
            End If
            Me.InvokeAsync("tem_fila", New Object() {filial}, Me.tem_filaOperationCompleted, userState)
        End Sub
        
        Private Sub Ontem_filaOperationCompleted(ByVal arg As Object)
            If (Not (Me.tem_filaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent tem_filaCompleted(Me, New tem_filaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.oticasanamaria.net.br/wins/trans_matriz_filial", RequestNamespace:="http://www.oticasanamaria.net.br/wins/", ResponseNamespace:="http://www.oticasanamaria.net.br/wins/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function trans_matriz_filial(ByVal filial As Integer) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("trans_matriz_filial", New Object() {filial})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub trans_matriz_filialAsync(ByVal filial As Integer)
            Me.trans_matriz_filialAsync(filial, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub trans_matriz_filialAsync(ByVal filial As Integer, ByVal userState As Object)
            If (Me.trans_matriz_filialOperationCompleted Is Nothing) Then
                Me.trans_matriz_filialOperationCompleted = AddressOf Me.Ontrans_matriz_filialOperationCompleted
            End If
            Me.InvokeAsync("trans_matriz_filial", New Object() {filial}, Me.trans_matriz_filialOperationCompleted, userState)
        End Sub
        
        Private Sub Ontrans_matriz_filialOperationCompleted(ByVal arg As Object)
            If (Not (Me.trans_matriz_filialCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent trans_matriz_filialCompleted(Me, New trans_matriz_filialCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.oticasanamaria.net.br/wins/trans_matriz_filial_nreg", RequestNamespace:="http://www.oticasanamaria.net.br/wins/", ResponseNamespace:="http://www.oticasanamaria.net.br/wins/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function trans_matriz_filial_nreg(ByVal filial As Integer, ByVal registros As Integer) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("trans_matriz_filial_nreg", New Object() {filial, registros})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub trans_matriz_filial_nregAsync(ByVal filial As Integer, ByVal registros As Integer)
            Me.trans_matriz_filial_nregAsync(filial, registros, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub trans_matriz_filial_nregAsync(ByVal filial As Integer, ByVal registros As Integer, ByVal userState As Object)
            If (Me.trans_matriz_filial_nregOperationCompleted Is Nothing) Then
                Me.trans_matriz_filial_nregOperationCompleted = AddressOf Me.Ontrans_matriz_filial_nregOperationCompleted
            End If
            Me.InvokeAsync("trans_matriz_filial_nreg", New Object() {filial, registros}, Me.trans_matriz_filial_nregOperationCompleted, userState)
        End Sub
        
        Private Sub Ontrans_matriz_filial_nregOperationCompleted(ByVal arg As Object)
            If (Not (Me.trans_matriz_filial_nregCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent trans_matriz_filial_nregCompleted(Me, New trans_matriz_filial_nregCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.oticasanamaria.net.br/wins/Marca_transmitido", RequestNamespace:="http://www.oticasanamaria.net.br/wins/", ResponseNamespace:="http://www.oticasanamaria.net.br/wins/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Marca_transmitido(ByVal id_fila As Integer, ByVal filial As Integer, ByVal dt As Date) As String
            Dim results() As Object = Me.Invoke("Marca_transmitido", New Object() {id_fila, filial, dt})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Marca_transmitidoAsync(ByVal id_fila As Integer, ByVal filial As Integer, ByVal dt As Date)
            Me.Marca_transmitidoAsync(id_fila, filial, dt, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Marca_transmitidoAsync(ByVal id_fila As Integer, ByVal filial As Integer, ByVal dt As Date, ByVal userState As Object)
            If (Me.Marca_transmitidoOperationCompleted Is Nothing) Then
                Me.Marca_transmitidoOperationCompleted = AddressOf Me.OnMarca_transmitidoOperationCompleted
            End If
            Me.InvokeAsync("Marca_transmitido", New Object() {id_fila, filial, dt}, Me.Marca_transmitidoOperationCompleted, userState)
        End Sub
        
        Private Sub OnMarca_transmitidoOperationCompleted(ByVal arg As Object)
            If (Not (Me.Marca_transmitidoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Marca_transmitidoCompleted(Me, New Marca_transmitidoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.oticasanamaria.net.br/wins/devolve_importados", RequestNamespace:="http://www.oticasanamaria.net.br/wins/", ResponseNamespace:="http://www.oticasanamaria.net.br/wins/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function devolve_importados(ByVal ds As System.Data.DataSet) As String
            Dim results() As Object = Me.Invoke("devolve_importados", New Object() {ds})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub devolve_importadosAsync(ByVal ds As System.Data.DataSet)
            Me.devolve_importadosAsync(ds, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub devolve_importadosAsync(ByVal ds As System.Data.DataSet, ByVal userState As Object)
            If (Me.devolve_importadosOperationCompleted Is Nothing) Then
                Me.devolve_importadosOperationCompleted = AddressOf Me.Ondevolve_importadosOperationCompleted
            End If
            Me.InvokeAsync("devolve_importados", New Object() {ds}, Me.devolve_importadosOperationCompleted, userState)
        End Sub
        
        Private Sub Ondevolve_importadosOperationCompleted(ByVal arg As Object)
            If (Not (Me.devolve_importadosCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent devolve_importadosCompleted(Me, New devolve_importadosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.oticasanamaria.net.br/wins/R360", RequestNamespace:="http://www.oticasanamaria.net.br/wins/", ResponseNamespace:="http://www.oticasanamaria.net.br/wins/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function R360(ByVal di As Date, ByVal df As Date) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("R360", New Object() {di, df})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub R360Async(ByVal di As Date, ByVal df As Date)
            Me.R360Async(di, df, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub R360Async(ByVal di As Date, ByVal df As Date, ByVal userState As Object)
            If (Me.R360OperationCompleted Is Nothing) Then
                Me.R360OperationCompleted = AddressOf Me.OnR360OperationCompleted
            End If
            Me.InvokeAsync("R360", New Object() {di, df}, Me.R360OperationCompleted, userState)
        End Sub
        
        Private Sub OnR360OperationCompleted(ByVal arg As Object)
            If (Not (Me.R360CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent R360Completed(Me, New R360CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.oticasanamaria.net.br/wins/cf", RequestNamespace:="http://www.oticasanamaria.net.br/wins/", ResponseNamespace:="http://www.oticasanamaria.net.br/wins/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function cf() As String
            Dim results() As Object = Me.Invoke("cf", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub cfAsync()
            Me.cfAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub cfAsync(ByVal userState As Object)
            If (Me.cfOperationCompleted Is Nothing) Then
                Me.cfOperationCompleted = AddressOf Me.OncfOperationCompleted
            End If
            Me.InvokeAsync("cf", New Object(-1) {}, Me.cfOperationCompleted, userState)
        End Sub
        
        Private Sub OncfOperationCompleted(ByVal arg As Object)
            If (Not (Me.cfCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent cfCompleted(Me, New cfCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.oticasanamaria.net.br/wins/RPontuacao", RequestNamespace:="http://www.oticasanamaria.net.br/wins/", ResponseNamespace:="http://www.oticasanamaria.net.br/wins/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RPontuacao(ByVal di As String, ByVal df As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("RPontuacao", New Object() {di, df})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RPontuacaoAsync(ByVal di As String, ByVal df As String)
            Me.RPontuacaoAsync(di, df, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RPontuacaoAsync(ByVal di As String, ByVal df As String, ByVal userState As Object)
            If (Me.RPontuacaoOperationCompleted Is Nothing) Then
                Me.RPontuacaoOperationCompleted = AddressOf Me.OnRPontuacaoOperationCompleted
            End If
            Me.InvokeAsync("RPontuacao", New Object() {di, df}, Me.RPontuacaoOperationCompleted, userState)
        End Sub
        
        Private Sub OnRPontuacaoOperationCompleted(ByVal arg As Object)
            If (Not (Me.RPontuacaoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RPontuacaoCompleted(Me, New RPontuacaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.oticasanamaria.net.br/wins/RGiro", RequestNamespace:="http://www.oticasanamaria.net.br/wins/", ResponseNamespace:="http://www.oticasanamaria.net.br/wins/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RGiro(ByVal xcod_tab As Integer, ByVal di As String, ByVal df As String, ByVal xFilial As Integer) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("RGiro", New Object() {xcod_tab, di, df, xFilial})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RGiroAsync(ByVal xcod_tab As Integer, ByVal di As String, ByVal df As String, ByVal xFilial As Integer)
            Me.RGiroAsync(xcod_tab, di, df, xFilial, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RGiroAsync(ByVal xcod_tab As Integer, ByVal di As String, ByVal df As String, ByVal xFilial As Integer, ByVal userState As Object)
            If (Me.RGiroOperationCompleted Is Nothing) Then
                Me.RGiroOperationCompleted = AddressOf Me.OnRGiroOperationCompleted
            End If
            Me.InvokeAsync("RGiro", New Object() {xcod_tab, di, df, xFilial}, Me.RGiroOperationCompleted, userState)
        End Sub
        
        Private Sub OnRGiroOperationCompleted(ByVal arg As Object)
            If (Not (Me.RGiroCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RGiroCompleted(Me, New RGiroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.oticasanamaria.net.br/wins/OS_Semana", RequestNamespace:="http://www.oticasanamaria.net.br/wins/", ResponseNamespace:="http://www.oticasanamaria.net.br/wins/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function OS_Semana(ByVal dias As Integer, ByRef ds As System.Data.DataSet) As String
            Dim results() As Object = Me.Invoke("OS_Semana", New Object() {dias, ds})
            ds = CType(results(1),System.Data.DataSet)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub OS_SemanaAsync(ByVal dias As Integer, ByVal ds As System.Data.DataSet)
            Me.OS_SemanaAsync(dias, ds, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub OS_SemanaAsync(ByVal dias As Integer, ByVal ds As System.Data.DataSet, ByVal userState As Object)
            If (Me.OS_SemanaOperationCompleted Is Nothing) Then
                Me.OS_SemanaOperationCompleted = AddressOf Me.OnOS_SemanaOperationCompleted
            End If
            Me.InvokeAsync("OS_Semana", New Object() {dias, ds}, Me.OS_SemanaOperationCompleted, userState)
        End Sub
        
        Private Sub OnOS_SemanaOperationCompleted(ByVal arg As Object)
            If (Not (Me.OS_SemanaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent OS_SemanaCompleted(Me, New OS_SemanaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.oticasanamaria.net.br/wins/exporta_produto", RequestNamespace:="http://www.oticasanamaria.net.br/wins/", ResponseNamespace:="http://www.oticasanamaria.net.br/wins/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function exporta_produto(ByVal ds As System.Data.DataSet, ByVal tipo As String, ByVal tab As Long) As String
            Dim results() As Object = Me.Invoke("exporta_produto", New Object() {ds, tipo, tab})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub exporta_produtoAsync(ByVal ds As System.Data.DataSet, ByVal tipo As String, ByVal tab As Long)
            Me.exporta_produtoAsync(ds, tipo, tab, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub exporta_produtoAsync(ByVal ds As System.Data.DataSet, ByVal tipo As String, ByVal tab As Long, ByVal userState As Object)
            If (Me.exporta_produtoOperationCompleted Is Nothing) Then
                Me.exporta_produtoOperationCompleted = AddressOf Me.Onexporta_produtoOperationCompleted
            End If
            Me.InvokeAsync("exporta_produto", New Object() {ds, tipo, tab}, Me.exporta_produtoOperationCompleted, userState)
        End Sub
        
        Private Sub Onexporta_produtoOperationCompleted(ByVal arg As Object)
            If (Not (Me.exporta_produtoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent exporta_produtoCompleted(Me, New exporta_produtoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.oticasanamaria.net.br/wins/os_in", RequestNamespace:="http://www.oticasanamaria.net.br/wins/", ResponseNamespace:="http://www.oticasanamaria.net.br/wins/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function os_in(ByVal tOS As System.Data.DataSet, ByVal dsTrat As System.Data.DataSet) As String
            Dim results() As Object = Me.Invoke("os_in", New Object() {tOS, dsTrat})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub os_inAsync(ByVal tOS As System.Data.DataSet, ByVal dsTrat As System.Data.DataSet)
            Me.os_inAsync(tOS, dsTrat, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub os_inAsync(ByVal tOS As System.Data.DataSet, ByVal dsTrat As System.Data.DataSet, ByVal userState As Object)
            If (Me.os_inOperationCompleted Is Nothing) Then
                Me.os_inOperationCompleted = AddressOf Me.Onos_inOperationCompleted
            End If
            Me.InvokeAsync("os_in", New Object() {tOS, dsTrat}, Me.os_inOperationCompleted, userState)
        End Sub
        
        Private Sub Onos_inOperationCompleted(ByVal arg As Object)
            If (Not (Me.os_inCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent os_inCompleted(Me, New os_inCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.oticasanamaria.net.br/wins/os_retrans", RequestNamespace:="http://www.oticasanamaria.net.br/wins/", ResponseNamespace:="http://www.oticasanamaria.net.br/wins/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function os_retrans(ByVal nOS As Integer, ByVal nFilial As Integer) As String
            Dim results() As Object = Me.Invoke("os_retrans", New Object() {nOS, nFilial})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub os_retransAsync(ByVal nOS As Integer, ByVal nFilial As Integer)
            Me.os_retransAsync(nOS, nFilial, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub os_retransAsync(ByVal nOS As Integer, ByVal nFilial As Integer, ByVal userState As Object)
            If (Me.os_retransOperationCompleted Is Nothing) Then
                Me.os_retransOperationCompleted = AddressOf Me.Onos_retransOperationCompleted
            End If
            Me.InvokeAsync("os_retrans", New Object() {nOS, nFilial}, Me.os_retransOperationCompleted, userState)
        End Sub
        
        Private Sub Onos_retransOperationCompleted(ByVal arg As Object)
            If (Not (Me.os_retransCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent os_retransCompleted(Me, New os_retransCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.oticasanamaria.net.br/wins/os_Out", RequestNamespace:="http://www.oticasanamaria.net.br/wins/", ResponseNamespace:="http://www.oticasanamaria.net.br/wins/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function os_Out(ByVal nOS As Integer, ByVal nFilial As Integer) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("os_Out", New Object() {nOS, nFilial})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub os_OutAsync(ByVal nOS As Integer, ByVal nFilial As Integer)
            Me.os_OutAsync(nOS, nFilial, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub os_OutAsync(ByVal nOS As Integer, ByVal nFilial As Integer, ByVal userState As Object)
            If (Me.os_OutOperationCompleted Is Nothing) Then
                Me.os_OutOperationCompleted = AddressOf Me.Onos_OutOperationCompleted
            End If
            Me.InvokeAsync("os_Out", New Object() {nOS, nFilial}, Me.os_OutOperationCompleted, userState)
        End Sub
        
        Private Sub Onos_OutOperationCompleted(ByVal arg As Object)
            If (Not (Me.os_OutCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent os_OutCompleted(Me, New os_OutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.oticasanamaria.net.br/wins/os_Out_labo", RequestNamespace:="http://www.oticasanamaria.net.br/wins/", ResponseNamespace:="http://www.oticasanamaria.net.br/wins/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function os_Out_labo(ByVal nOS As Integer, ByVal nFilial As Integer) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("os_Out_labo", New Object() {nOS, nFilial})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub os_Out_laboAsync(ByVal nOS As Integer, ByVal nFilial As Integer)
            Me.os_Out_laboAsync(nOS, nFilial, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub os_Out_laboAsync(ByVal nOS As Integer, ByVal nFilial As Integer, ByVal userState As Object)
            If (Me.os_Out_laboOperationCompleted Is Nothing) Then
                Me.os_Out_laboOperationCompleted = AddressOf Me.Onos_Out_laboOperationCompleted
            End If
            Me.InvokeAsync("os_Out_labo", New Object() {nOS, nFilial}, Me.os_Out_laboOperationCompleted, userState)
        End Sub
        
        Private Sub Onos_Out_laboOperationCompleted(ByVal arg As Object)
            If (Not (Me.os_Out_laboCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent os_Out_laboCompleted(Me, New os_Out_laboCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub Importa_produtoCompletedEventHandler(ByVal sender As Object, ByVal e As Importa_produtoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Importa_produtoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub Saldo_produtoCompletedEventHandler(ByVal sender As Object, ByVal e As Saldo_produtoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Saldo_produtoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub incluir_listagem_estoqueCompletedEventHandler(ByVal sender As Object, ByVal e As incluir_listagem_estoqueCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class incluir_listagem_estoqueCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub logarCompletedEventHandler(ByVal sender As Object, ByVal e As logarCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class logarCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub os_com_andamentosCompletedEventHandler(ByVal sender As Object, ByVal e As os_com_andamentosCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class os_com_andamentosCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub Andamentos_labonorte_matrizCompletedEventHandler(ByVal sender As Object, ByVal e As Andamentos_labonorte_matrizCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Andamentos_labonorte_matrizCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property ds() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub trans_filial_matrizCompletedEventHandler(ByVal sender As Object, ByVal e As trans_filial_matrizCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class trans_filial_matrizCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub trans_filial_matriz_dsCompletedEventHandler(ByVal sender As Object, ByVal e As trans_filial_matriz_dsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class trans_filial_matriz_dsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property dsRet() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub tem_filaCompletedEventHandler(ByVal sender As Object, ByVal e As tem_filaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class tem_filaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub trans_matriz_filialCompletedEventHandler(ByVal sender As Object, ByVal e As trans_matriz_filialCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class trans_matriz_filialCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub trans_matriz_filial_nregCompletedEventHandler(ByVal sender As Object, ByVal e As trans_matriz_filial_nregCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class trans_matriz_filial_nregCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub Marca_transmitidoCompletedEventHandler(ByVal sender As Object, ByVal e As Marca_transmitidoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Marca_transmitidoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub devolve_importadosCompletedEventHandler(ByVal sender As Object, ByVal e As devolve_importadosCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class devolve_importadosCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub R360CompletedEventHandler(ByVal sender As Object, ByVal e As R360CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class R360CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub cfCompletedEventHandler(ByVal sender As Object, ByVal e As cfCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class cfCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub RPontuacaoCompletedEventHandler(ByVal sender As Object, ByVal e As RPontuacaoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RPontuacaoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub RGiroCompletedEventHandler(ByVal sender As Object, ByVal e As RGiroCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RGiroCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub OS_SemanaCompletedEventHandler(ByVal sender As Object, ByVal e As OS_SemanaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class OS_SemanaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property ds() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub exporta_produtoCompletedEventHandler(ByVal sender As Object, ByVal e As exporta_produtoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class exporta_produtoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub os_inCompletedEventHandler(ByVal sender As Object, ByVal e As os_inCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class os_inCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub os_retransCompletedEventHandler(ByVal sender As Object, ByVal e As os_retransCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class os_retransCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub os_OutCompletedEventHandler(ByVal sender As Object, ByVal e As os_OutCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class os_OutCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub os_Out_laboCompletedEventHandler(ByVal sender As Object, ByVal e As os_Out_laboCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class os_Out_laboCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
End Namespace
