'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace labonorte
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="labonorte.IService1")>  _
    Public Interface IService1
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetData", ReplyAction:="http://tempuri.org/IService1/GetDataResponse")>  _
        Function GetData(ByVal value As Integer) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/andamentos", ReplyAction:="http://tempuri.org/IService1/andamentosResponse")>  _
        Function andamentos(ByVal filial As Integer, ByVal xos As Integer) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/FilaRetorno", ReplyAction:="http://tempuri.org/IService1/FilaRetornoResponse")>  _
        Function FilaRetorno(ByVal filial As Integer, ByVal nReg As Integer) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/FilaEnvio", ReplyAction:="http://tempuri.org/IService1/FilaEnvioResponse")>  _
        Function FilaEnvio(ByVal tb As System.Data.DataTable, ByVal filial As Integer, ByRef strLog As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/devolve_importados", ReplyAction:="http://tempuri.org/IService1/devolve_importadosResponse")>  _
        Function devolve_importados(ByVal tb As System.Data.DataTable) As String
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IService1Channel
        Inherits labonorte.IService1, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class Service1Client
        Inherits System.ServiceModel.ClientBase(Of labonorte.IService1)
        Implements labonorte.IService1
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetData(ByVal value As Integer) As String Implements labonorte.IService1.GetData
            Return MyBase.Channel.GetData(value)
        End Function
        
        Public Function andamentos(ByVal filial As Integer, ByVal xos As Integer) As System.Data.DataTable Implements labonorte.IService1.andamentos
            Return MyBase.Channel.andamentos(filial, xos)
        End Function
        
        Public Function FilaRetorno(ByVal filial As Integer, ByVal nReg As Integer) As System.Data.DataTable Implements labonorte.IService1.FilaRetorno
            Return MyBase.Channel.FilaRetorno(filial, nReg)
        End Function
        
        Public Function FilaEnvio(ByVal tb As System.Data.DataTable, ByVal filial As Integer, ByRef strLog As String) As System.Data.DataTable Implements labonorte.IService1.FilaEnvio
            Return MyBase.Channel.FilaEnvio(tb, filial, strLog)
        End Function
        
        Public Function devolve_importados(ByVal tb As System.Data.DataTable) As String Implements labonorte.IService1.devolve_importados
            Return MyBase.Channel.devolve_importados(tb)
        End Function
    End Class
End Namespace
